const PDFDocument = require('pdfkit');
const ExcelJS = require('exceljs');
const { query } = require('../config/database');
const { uploadPDF } = require('../config/cloudinary');
const { logger } = require('../utils/logger');

const GHS = (n) => `GH₵ ${parseFloat(n || 0).toFixed(2)}`;
const dateStr = (d) => d ? new Date(d).toLocaleDateString('en-GH') : '—';
const dateTimeStr = (d) => d ? new Date(d).toLocaleString('en-GH') : '—';

// ── Brand Colors ──────────────────────────────────────────────
const COLORS = {
  primary: '#006B5E',
  secondary: '#FFB300',
  text: '#1A1A1A',
  muted: '#666666',
  light: '#F5F5F5',
  success: '#2E7D32',
  error: '#BA1A1A',
  warning: '#E65100', // matches AppTheme.warningColor in the Flutter app — keep in sync
};

// Maps a transaction status to its display color consistently across
// every report/receipt in this file, so a status never silently reads
// as a binary success/failure by accident (e.g. pending_confirmation
// must never render the same color as a definite failure — see
// migration 002_ussd_single_dial_redesign.sql for why that distinction
// matters).
function statusColor(status) {
  if (status === 'success') return COLORS.success;
  if (status === 'pending_confirmation' || status === 'processing' || status === 'initiated') return COLORS.warning;
  return COLORS.error; // failed, reversed, or any unrecognized status
}

// ── Transaction Receipt PDF ───────────────────────────────────

async function generateTransactionReceipt(transaction) {
  // Defense-in-depth: the current (and only) caller already gates this
  // to confirmed successes only, but a "receipt" is a formal document
  // that can outlive the app session and be shown to a customer or used
  // in a dispute. If some future caller (e.g. an admin "regenerate
  // receipt" action) ever invokes this directly without re-checking
  // status first, a pending_confirmation transaction must never be
  // rendered as a binary success/failure receipt — we genuinely don't
  // know the outcome, and a formal document saying "FAILED" could be
  // actively wrong if the transaction actually succeeded.
  if (transaction.status !== 'success') {
    logger.warn(`generateTransactionReceipt called for non-success transaction ${transaction.id} (status: ${transaction.status}) — refusing to generate a misleading receipt`);
    return null;
  }

  try {
    const doc = new PDFDocument({ size: 'A6', margin: 20 });
    const buffers = [];
    doc.on('data', b => buffers.push(b));

    await new Promise((resolve) => {
      doc.on('end', resolve);

      // Header
      doc.rect(0, 0, doc.page.width, 60).fill(COLORS.primary);
      doc.fillColor('white').fontSize(14).font('Helvetica-Bold')
        .text('Agent Pro Ghana', 20, 14, { align: 'center' });
      doc.fontSize(8).font('Helvetica')
        .text('One App. Every Mobile Money Business.', 20, 30, { align: 'center' });
      doc.fillColor(COLORS.text);

      // Transaction status badge — guard above guarantees this is
      // always a confirmed success by the time we reach this point.
      doc.moveDown(2);
      doc.fontSize(11).fillColor(COLORS.success).font('Helvetica-Bold')
        .text('✓ SUCCESSFUL', { align: 'center' });

      // Amount
      doc.fontSize(22).fillColor(COLORS.text).font('Helvetica-Bold')
        .text(GHS(transaction.amount), { align: 'center' });

      doc.fontSize(9).fillColor(COLORS.muted).font('Helvetica')
        .text(
          (transaction.transaction_type || '').replace(/_/g, ' ').toUpperCase(),
          { align: 'center' }
        );

      // Divider
      doc.moveDown(0.5);
      doc.moveTo(20, doc.y).lineTo(doc.page.width - 20, doc.y)
        .strokeColor('#EEEEEE').stroke();
      doc.moveDown(0.5);

      // Details
      const details = [
        ['Reference', transaction.reference],
        ['Network Ref', transaction.network_reference || '—'],
        ['Provider', (transaction.provider || '').toUpperCase()],
        ['Customer', transaction.customer_name || transaction.customer_phone || '—'],
        ['Customer Phone', transaction.customer_phone || '—'],
        ['Agent', transaction.agent_name || '—'],
        ['Branch', transaction.branch_name || '—'],
        ['Date', dateTimeStr(transaction.created_at)],
        ['Completed', dateTimeStr(transaction.completed_at)],
      ];

      details.forEach(([label, value]) => {
        doc.fontSize(8).fillColor(COLORS.muted).font('Helvetica')
          .text(label, 20, doc.y, { width: 100, continued: true });
        doc.fillColor(COLORS.text).font('Helvetica-Bold')
          .text(value || '—', { align: 'right' });
        doc.moveDown(0.3);
      });

      // Footer
      doc.moveTo(20, doc.page.height - 40).lineTo(doc.page.width - 20, doc.page.height - 40)
        .strokeColor('#EEEEEE').stroke();
      doc.fontSize(7).fillColor(COLORS.muted).font('Helvetica')
        .text('This is an electronic receipt generated by Agent Pro Ghana.',
          20, doc.page.height - 32, { align: 'center' });
      doc.text('support@agentproghana.com', { align: 'center' });

      doc.end();
    });

    const buffer = Buffer.concat(buffers);
    const filename = `receipt_${transaction.reference}_${Date.now()}`;
    const url = await uploadPDF(buffer, filename);
    return url;
  } catch (error) {
    logger.error('Receipt generation error:', error);
    return null;
  }
}

// ── Transaction Report PDF ────────────────────────────────────

async function generateTransactionReportPDF({ transactions, filters, summary, title }) {
  const doc = new PDFDocument({ size: 'A4', margin: 40 });
  const buffers = [];
  doc.on('data', b => buffers.push(b));

  await new Promise((resolve) => {
    doc.on('end', resolve);

    // Header
    doc.rect(0, 0, doc.page.width, 70).fill(COLORS.primary);
    doc.fillColor('white').fontSize(18).font('Helvetica-Bold')
      .text('Agent Pro Ghana', 40, 15);
    doc.fontSize(11).font('Helvetica')
      .text(title || 'Transaction Report', 40, 35);
    doc.fontSize(9)
      .text(`Generated: ${dateTimeStr(new Date())}`, 40, 52);

    doc.fillColor(COLORS.text);
    doc.moveDown(2.5);

    // Summary Cards
    const summaries = [
      ['Total Transactions', summary.count || 0],
      ['Total Amount', GHS(summary.total_amount)],
      ['Net Commission', GHS(summary.total_commission)],
      ['Success Rate', `${summary.success_rate || 0}%`],
    ];

    const cardWidth = (doc.page.width - 80 - 30) / 4;
    summaries.forEach(([label, value], i) => {
      const x = 40 + i * (cardWidth + 10);
      const y = doc.y;
      doc.rect(x, y, cardWidth, 48).fill(COLORS.light);
      doc.fontSize(7).fillColor(COLORS.muted).font('Helvetica')
        .text(label, x + 6, y + 8, { width: cardWidth - 12 });
      doc.fontSize(12).fillColor(COLORS.primary).font('Helvetica-Bold')
        .text(String(value), x + 6, y + 20, { width: cardWidth - 12 });
    });

    doc.moveDown(3.5);

    // Table Header
    const cols = [
      { label: 'Date', width: 80 },
      { label: 'Reference', width: 100 },
      { label: 'Type', width: 70 },
      { label: 'Provider', width: 55 },
      { label: 'Customer', width: 90 },
      { label: 'Amount', width: 65 },
      { label: 'Status', width: 55 },
    ];

    doc.rect(40, doc.y, doc.page.width - 80, 18).fill(COLORS.primary);
    let x = 40;
    cols.forEach(col => {
      doc.fontSize(7.5).fillColor('white').font('Helvetica-Bold')
        .text(col.label, x + 4, doc.y - 14, { width: col.width - 4 });
      x += col.width;
    });
    doc.moveDown(0.2);

    // Table rows
    transactions.forEach((tx, idx) => {
      if (doc.y > doc.page.height - 80) {
        doc.addPage();
        doc.moveDown(1);
      }

      const rowY = doc.y;
      if (idx % 2 === 0) {
        doc.rect(40, rowY, doc.page.width - 80, 16).fill('#FAFAFA');
      }

      const rowData = [
        dateStr(tx.created_at),
        tx.reference,
        (tx.transaction_type || '').replace('_', ' '),
        (tx.provider || '').toUpperCase(),
        tx.customer_phone || '—',
        GHS(tx.amount),
        (tx.status || '').toUpperCase(),
      ];

      x = 40;
      rowData.forEach((val, i) => {
        const color = i === 6 ? statusColor(tx.status) : COLORS.text;
        doc.fontSize(7).fillColor(color).font('Helvetica')
          .text(val, x + 4, rowY + 4, { width: cols[i].width - 4 });
        x += cols[i].width;
      });

      doc.y = rowY + 18;
    });

    doc.end();
  });

  return Buffer.concat(buffers);
}

// ── Transaction Report Excel ──────────────────────────────────

async function generateTransactionReportExcel({ transactions, filters, summary, title }) {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'Agent Pro Ghana';
  workbook.created = new Date();

  const sheet = workbook.addWorksheet('Transactions', {
    pageSetup: { paperSize: 9, orientation: 'landscape' },
  });

  // Title
  sheet.mergeCells('A1:H1');
  sheet.getCell('A1').value = title || 'Agent Pro Ghana — Transaction Report';
  sheet.getCell('A1').font = { size: 14, bold: true, color: { argb: 'FF006B5E' } };
  sheet.getCell('A1').alignment = { horizontal: 'center' };

  sheet.mergeCells('A2:H2');
  sheet.getCell('A2').value = `Generated: ${dateTimeStr(new Date())}`;
  sheet.getCell('A2').font = { size: 9, color: { argb: 'FF666666' } };
  sheet.getCell('A2').alignment = { horizontal: 'center' };

  // Summary row
  sheet.addRow([]);
  sheet.addRow(['Summary']);
  sheet.addRow(['Total Transactions', summary.count, '', 'Total Amount', `GH₵ ${parseFloat(summary.total_amount||0).toFixed(2)}`, '', 'Net Commission', `GH₵ ${parseFloat(summary.total_commission||0).toFixed(2)}`]);

  sheet.addRow([]);

  // Headers
  const headerRow = sheet.addRow([
    'Date', 'Reference', 'Network Ref', 'Transaction Type',
    'Provider', 'Customer Phone', 'Customer Name', 'Amount (GH₵)',
    'Commission (GH₵)', 'Status', 'Agent', 'Branch',
  ]);
  headerRow.eachCell(cell => {
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF006B5E' } };
    cell.font = { bold: true, color: { argb: 'FFFFFFFF' } };
    cell.border = { bottom: { style: 'thin' } };
  });

  // Data rows
  transactions.forEach((tx, i) => {
    const row = sheet.addRow([
      tx.created_at ? new Date(tx.created_at) : '',
      tx.reference,
      tx.network_reference || '',
      (tx.transaction_type || '').replace(/_/g, ' '),
      (tx.provider || '').toUpperCase(),
      tx.customer_phone || '',
      tx.customer_name || '',
      parseFloat(tx.amount || 0),
      parseFloat(tx.net_commission || 0),
      (tx.status || '').toUpperCase(),
      tx.agent_name || '',
      tx.branch_name || '',
    ]);

    if (i % 2 === 0) {
      row.eachCell(cell => {
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF5F5F5' } };
      });
    }

    // Color status — keep in sync with statusColor() used by the PDF
    // report above and AppTheme.statusColor() in the Flutter app.
    const statusCell = row.getCell(10);
    if (tx.status === 'success') statusCell.font = { color: { argb: 'FF2E7D32' }, bold: true };
    if (tx.status === 'failed') statusCell.font = { color: { argb: 'FFBA1A1A' }, bold: true };
    if (tx.status === 'pending_confirmation') statusCell.font = { color: { argb: 'FFE65100' }, bold: true };
  });

  // Column widths
  sheet.columns = [
    { width: 18 }, { width: 22 }, { width: 18 }, { width: 20 },
    { width: 12 }, { width: 16 }, { width: 20 }, { width: 14 },
    { width: 16 }, { width: 12 }, { width: 20 }, { width: 20 },
  ];

  // Format date and amount columns
  sheet.getColumn(1).numFmt = 'dd/mm/yyyy hh:mm';
  sheet.getColumn(8).numFmt = '#,##0.00';
  sheet.getColumn(9).numFmt = '#,##0.00';

  return workbook.xlsx.writeBuffer();
}

// ── Commission Report PDF ─────────────────────────────────────

async function generateCommissionReportPDF({ commissions, summary, title, groupBy }) {
  const doc = new PDFDocument({ size: 'A4', margin: 40 });
  const buffers = [];
  doc.on('data', b => buffers.push(b));

  await new Promise((resolve) => {
    doc.on('end', resolve);

    doc.rect(0, 0, doc.page.width, 70).fill(COLORS.primary);
    doc.fillColor('white').fontSize(18).font('Helvetica-Bold')
      .text('Agent Pro Ghana', 40, 15);
    doc.fontSize(11).font('Helvetica')
      .text(title || 'Commission Report', 40, 35);
    doc.fontSize(9).text(`Generated: ${dateTimeStr(new Date())}`, 40, 52);
    doc.fillColor(COLORS.text);
    doc.moveDown(3);

    // Summary
    doc.fontSize(9).font('Helvetica-Bold').text('Summary');
    doc.moveDown(0.3);
    [
      ['Gross Commission:', GHS(summary.total_gross)],
      ['Provider Share:', GHS(summary.total_provider_share)],
      ['Net Commission:', GHS(summary.total_net)],
      ['Transactions:', String(summary.transaction_count || 0)],
    ].forEach(([label, val]) => {
      doc.fontSize(8).fillColor(COLORS.muted).font('Helvetica')
        .text(label, 40, doc.y, { width: 140, continued: true });
      doc.fillColor(COLORS.text).font('Helvetica-Bold').text(val);
      doc.moveDown(0.2);
    });

    doc.moveDown(1);

    // Table
    const cols = [
      { label: groupBy === 'agent' ? 'Agent' : groupBy === 'branch' ? 'Branch' : 'Period', width: 140 },
      { label: 'Transactions', width: 80 },
      { label: 'Gross', width: 85 },
      { label: 'Provider Share', width: 90 },
      { label: 'Net Commission', width: 100 },
    ];

    doc.rect(40, doc.y, doc.page.width - 80, 18).fill(COLORS.primary);
    let x = 40;
    cols.forEach(col => {
      doc.fontSize(7.5).fillColor('white').font('Helvetica-Bold')
        .text(col.label, x + 4, doc.y - 14, { width: col.width - 4 });
      x += col.width;
    });
    doc.moveDown(0.2);

    commissions.forEach((row, idx) => {
      if (doc.y > doc.page.height - 60) doc.addPage();
      const rowY = doc.y;
      if (idx % 2 === 0) doc.rect(40, rowY, doc.page.width - 80, 16).fill('#FAFAFA');

      const vals = [
        row.label || row.period || '—',
        String(row.transaction_count || 0),
        GHS(row.total_gross),
        GHS(row.total_provider_share),
        GHS(row.total_net),
      ];

      x = 40;
      vals.forEach((val, i) => {
        doc.fontSize(7.5).fillColor(COLORS.text).font('Helvetica')
          .text(val, x + 4, rowY + 4, { width: cols[i].width - 4 });
        x += cols[i].width;
      });
      doc.y = rowY + 18;
    });

    doc.end();
  });

  return Buffer.concat(buffers);
}

// ── CSV Generator ─────────────────────────────────────────────

function generateCSV(data, columns) {
  const header = columns.map(c => `"${c.label}"`).join(',');
  const rows = data.map(row =>
    columns.map(c => {
      const val = c.getValue ? c.getValue(row) : (row[c.key] ?? '');
      return `"${String(val).replace(/"/g, '""')}"`;
    }).join(',')
  );
  return [header, ...rows].join('\n');
}

module.exports = {
  generateTransactionReceipt,
  generateTransactionReportPDF,
  generateTransactionReportExcel,
  generateCommissionReportPDF,
  generateCSV,
};
